# Generated by Django 5.0.1 on 2024-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid_premium',
            field=models.BooleanField(default=False),
        ),
    ]
