# Generated by Django 5.0.1 on 2024-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=255, unique=True)),
                ('date_scraped', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('min_salary', models.FloatField(default=None, null=True)),
                ('max_salary', models.FloatField(default=None, null=True)),
                ('salary_unit', models.TextField(default=None, null=True)),
                ('job_types', models.TextField(default=None, null=True)),
                ('job_description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
