# Generated by Django 5.0.1 on 2024-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='job_types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='max_salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='min_salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='salary_unit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
