# Generated by Django 5.0.1 on 2024-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscraper', '0002_alter_scrapeddata_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
